# =============================
# Spring Cloud Gateway 网关服务配置
# =============================

spring:
  application:
    name: gateway-service  # 应用名称，注册到Nacos
  main:
    allow-bean-definition-overriding: true  # 允许Bean覆盖，避免因Bean冲突导致启动失败
  autoconfigure:
    exclude:  # 禁用数据库相关自动配置，网关无需数据库
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER  # 兼容老版路径匹配
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos服务地址
        namespace: d0e61529-b169-481a-8e64-6c652f5729c8  # Nacos命名空间
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: d0e61529-b169-481a-8e64-6c652f5729c8
    gateway:
      # =============================
      # 路由配置：所有微服务转发规则
      # =============================
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: template-service
          uri: lb://template-service
          predicates:
            - Path=/api/templates/**
          filters:
            - StripPrefix=1
            
        - id: template-file-service
          uri: lb://template-service
          predicates:
            - Path=/api/templates/template-files/**
          filters:
            - StripPrefix=2
            - RewritePath=/template-files/(?<segment>.*), /template-files/${segment}
        - id: resume-service
          uri: lb://resume-service
          predicates:
            - Path=/api/resumes/**
          filters:
            - StripPrefix=2
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=2
        - id: admin-api
          uri: lb://user-service
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2
        - id: system-api
          uri: lb://gateway-service
          predicates:
            - Path=/api/status, /api/config/refresh
          filters:
            - StripPrefix=1
      # =============================
      # 全局CORS配置，允许跨域
      # =============================
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      # =============================
      # 网关HTTP客户端参数
      # =============================
      httpclient:
        max-header-size: 131072
        response-timeout: 60000
        connect-timeout: 30000
      # =============================
      # 服务发现自动路由
      # =============================
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

gateway:
  security:
    ignore-urls:
      - /api/auth/login
      - /login
      - /api/auth/register
      - /api/auth/captcha
      - /api/auth/refresh
      - /api/users/register
      - /api/templates/categories
      - /api/templates
      - /*/v2/api-docs
      - /*/v3/api-docs
      - /v2/api-docs
      - /v3/api-docs
      - /swagger-ui/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /webjars/**
      - /doc.html
      - /**/swagger-ui/**
      - /**/swagger-ui.html
      - /**/swagger-resources/**
      - /**/webjars/**
      - /**/doc.html

# =============================
# 服务端口与HTTP参数
# =============================
server:
  port: 9000  # 网关端口
  max-http-header-size: 131072
  undertow:
    max-http-post-size: 10485760  # 10MB
    max-http-header-size: 131072

# =============================
# JWT配置
# =============================
jwt:
  secret: ptu-resume-system-secret-key-for-jwt-token-generation-and-verification
  token-validity-in-seconds: 86400  # token有效期1天
  refresh-token-validity-in-seconds: 604800  # refresh token有效期7天

# =============================
# Sentinel流控配置
# =============================
sentinel:
  transport:
    dashboard: localhost:8858
  eager: true
  scg:
    fallback:
      mode: response
      response-status: 429
      response-body: '{"code":429,"message":"请求过于频繁，请稍后重试","data":null}'

# =============================
# 日志配置
# =============================
logging:
  level:
    root: INFO
    com.ptu.gateway: DEBUG
    com.ptu.gateway.filter: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# =============================
# MinIO配置（网关禁用）
# =============================
minio:
  enabled: false
  endpoint: "" 