server:
  port: 8089

spring:
  application:
    name: ai-service
  # 添加路径匹配策略，解决Swagger文档生成问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # Sentinel标准配置
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858

  datasource:
    url: jdbc:mysql://localhost:3306/resume_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

ai:
  deepseek:
    api-url: https://api.deepseek.com/v1/chat/completions
    api-key: sk-5d173fbaef3143d28394aedc571c1c61
    timeout: 30s

# Feign配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
  httpclient:
    enabled: true

# JWT配置（如需）
# jwt:
#   secret: xxx
#   expire: 86400

