server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  # 禁用数据源自动配置
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0
            
        # 简历服务路由
        - id: resume-service
          uri: lb://resume-service
          predicates:
            - Path=/resume/**
          filters:
            - StripPrefix=0
            
        # 认证服务路由
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
            
        # 模板服务路由
        - id: template-service
          uri: lb://template-service
          predicates:
            - Path=/template/**
          filters:
            - StripPrefix=0
            
        # 订单服务路由
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=0
            
        # AI服务路由
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=0
            
        # 文件服务路由
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=0
            
        # 通知服务路由
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=0
      
  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000

# 安全配置
security:
  ignore:
    whites:
      - /auth/login
      - /auth/register
      - /auth/health
      - /*/health
      - /*/actuator/**
      - /*/v3/api-docs
      - /*/swagger-ui.html
      - /*/swagger-ui/**

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always