server:
  port: 8000

spring:
  application:
    name: gateway-service
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  
  # 网关配置
  cloud:
    # Nacos服务发现配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: d0e61529-b169-481a-8e64-6c652f5729c8
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: d0e61529-b169-481a-8e64-6c652f5729c8
    
    # Gateway配置
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现
          lower-case-service-id: true  # 服务名小写
      
      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
            
      # 路由配置
      routes:
        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            
        # 认证服务路由
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            
        # 文件服务路由
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
            
        # 订单服务路由
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            
        # 模板服务路由
        - id: template-service
          uri: lb://template-service
          predicates:
            - Path=/template/**
          filters:
            - StripPrefix=1
            
        # 简历服务路由
        - id: resume-service
          uri: lb://resume-service
          predicates:
            - Path=/resume/**
          filters:
            - StripPrefix=1
            
        # AI服务路由
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1
            
        # 通知服务路由
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
    
    # Sentinel配置
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true
      # 网关流控适配
      scg:
        fallback:
          mode: response
          response-status: 429
          response-body: '{"code":429,"message":"请求过于频繁，请稍后重试","success":false}'

# 白名单接口配置，这些路径无需认证
gateway:
  security:
    ignore-urls:
      - /auth/login
      - /auth/register
      - /auth/captcha
      - /*/v3/api-docs
      - /swagger-ui.html
      - /swagger-resources/**
      - /webjars/**
      - /actuator/** 