server:
  port: 8005 

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/resume_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    
  # Sentinel标准配置
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858

minio:
  endpoint: http://127.0.0.1:9090
  access-key: ZMlUgS6Z3d4raCN3pVeT
  secret-key: VOHLtWjk1WBFdiCpG06VPVTVgKsSp5Nl9w2D8vg8
  bucket:
    template: resume-templates
    thumbnail: resume-thumbnails

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ptu.order.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 